spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-api
    username: postgres
    password: RafaAdmin21.
  jpa:
    hibernate:
      ddl-auto: create
